server:
  port: 12000
spring:
  application:
    name: toor-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CourtOfSpeech/test-config.git
  rabbitmq:
    host: 192.168.205.128
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh